/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AuthButtonGroup: typeof import('./src/components/auth/AuthButtonGroup.vue')['default']
    AuthHeader: typeof import('./src/components/auth/AuthHeader.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    CaptchaInput: typeof import('./src/components/CaptchaInput.vue')['default']
    CategoryEditDialog: typeof import('./src/components/item/CategoryEditDialog.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CopyrightFooter: typeof import('./src/components/CopyrightFooter.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EnhancedInput: typeof import('./src/components/EnhancedInput.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputDialog: typeof import('./src/components/InputDialog.vue')['default']
    ItemDetailDialog: typeof import('./src/components/item/ItemDetailDialog.vue')['default']
    ItemTakeOutDialog: typeof import('./src/components/item/ItemTakeOutDialog.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    MessageComponent: typeof import('./src/components/MessageComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SortControl: typeof import('./src/components/SortControl.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    UnitEditDialog: typeof import('./src/components/unit/UnitEditDialog.vue')['default']
    UnitListDialog: typeof import('./src/components/unit/UnitListDialog.vue')['default']
    UnitTypeEditDialog: typeof import('./src/components/unit/UnitTypeEditDialog.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
