/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiMessageContent: typeof import('./src/components/ai/AiMessageContent.vue')['default']
    AuthButtonGroup: typeof import('./src/components/auth/AuthButtonGroup.vue')['default']
    AuthHeader: typeof import('./src/components/auth/AuthHeader.vue')['default']
    Avatar: typeof import('./src/components/Avatar.vue')['default']
    CapacityGaugeGroup: typeof import('./src/components/data-center/CapacityGaugeGroup.vue')['default']
    CaptchaInput: typeof import('./src/components/CaptchaInput.vue')['default']
    CategoryPieChart: typeof import('./src/components/data-center/CategoryPieChart.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CopyrightFooter: typeof import('./src/components/CopyrightFooter.vue')['default']
    CustomButton: typeof import('./src/components/CustomButton.vue')['default']
    CustomSelect: typeof import('./src/components/CustomSelect.vue')['default']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCollapseTransition: typeof import('element-plus/es')['ElCollapseTransition']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSegmented: typeof import('element-plus/es')['ElSegmented']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeline: typeof import('element-plus/es')['ElTimeline']
    ElTimelineItem: typeof import('element-plus/es')['ElTimelineItem']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EnhancedInput: typeof import('./src/components/EnhancedInput.vue')['default']
    ExpiringItemTable: typeof import('./src/components/data-center/ExpiringItemTable.vue')['default']
    FreshnessPieChart: typeof import('./src/components/data-center/FreshnessPieChart.vue')['default']
    FridgeCreateDialog: typeof import('./src/components/fridge/FridgeCreateDialog.vue')['default']
    FridgeItemBarChart: typeof import('./src/components/data-center/FridgeItemBarChart.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputDialog: typeof import('./src/components/InputDialog.vue')['default']
    ItemDetailDialog: typeof import('./src/components/item/ItemDetailDialog.vue')['default']
    ItemTakeOutDialog: typeof import('./src/components/item/ItemTakeOutDialog.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    LogoButton: typeof import('./src/components/LogoButton.vue')['default']
    MessageComponent: typeof import('./src/components/MessageComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    ShelfLifeBarChart: typeof import('./src/components/data-center/ShelfLifeBarChart.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SortControl: typeof import('./src/components/SortControl.vue')['default']
    StatCard: typeof import('./src/components/data-center/StatCard.vue')['default']
    ThemeToggle: typeof import('./src/components/ThemeToggle.vue')['default']
    TrendLineChart: typeof import('./src/components/data-center/TrendLineChart.vue')['default']
    UnitListDialog: typeof import('./src/components/unit/UnitListDialog.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
